-- HIS 门诊医生站数据结构 DDL
-- 基于: F:\HospitalStats\HIS数据库相关文档\HIS门诊医生站数据结构.txt
-- Schema: HOSPITAL

-- 1.1 门诊病历记录 OUTP_MR
-- 病人每次就诊产生一条记录。主键：就诊时间，就诊序号。
CREATE TABLE HOSPITAL.OUTP_MR (
    PATIENT_ID    VARCHAR2(10)  NOT NULL,
    VISIT_DATE    DATE          NOT NULL,
    VISIT_NO      NUMBER(4)     NOT NULL,
    ILLNESS_DESC  VARCHAR2(200),
    ANAMNESIS     VARCHAR2(80),
    FAMILY_ILL    VARCHAR2(80),
    MARRITAL      VARCHAR2(4),
    INDIVIDUDL    VARCHAR2(80),
    MENSES        VARCHAR2(80),
    MED_HISTORY   VARCHAR2(2000),
    BODY_EXAM     VARCHAR2(1000),
    DIAG_DESC     VARCHAR2(80),
    ADVICE        VARCHAR2(600),
    DOCTOR        VARCHAR2(8),
    CONSTRAINT PK_OUTP_MR PRIMARY KEY (VISIT_DATE, VISIT_NO)
);

-- 1.2 门诊病人诊疗费用项目 OUTP_BILL_ITEMS_DOCTOR
-- 门诊病人费用的明细记录。主键：就诊日期、就诊序号、序号。
CREATE TABLE HOSPITAL.OUTP_BILL_ITEMS_DOCTOR (
    VISIT_DATE       DATE          NOT NULL,
    VISIT_NO         NUMBER(4)     NOT NULL,
    RCPT_NO          VARCHAR2(8),
    ITEM_NO          NUMBER(2)     NOT NULL,
    ITEM_CLASS       VARCHAR2(1),
    CLASS_ON_RCPT    VARCHAR2(1),
    ITEM_CODE        VARCHAR2(10),
    ITEM_NAME        VARCHAR2(40),
    ITEM_SPEC        VARCHAR2(20),
    AMOUNT           NUMBER(6,2),
    UNITS            VARCHAR2(8),
    PERFORMED_BY     VARCHAR2(8),
    COSTS            NUMBER(8,2),
    CHARGES          NUMBER(8,2),
    CFLAG            VARCHAR2(1),
    UNIT_PRICE       NUMBER(7,3),
    FL_ITEM_COSTS    NUMBER(7,3),
    JY_ITEM_COSTS    NUMBER(7,3),
    PREC_NO          NUMBER(4),
    DOCTOR_NO        VARCHAR2(4),
    CONSTRAINT PK_OUTP_BILL_ITEMS_DOCTOR PRIMARY KEY (VISIT_DATE, VISIT_NO, ITEM_NO)
);

-- 1.3 诊室候诊排队记录 OUTP_WAIT_QUEUE
-- 分诊挂号时产生，门诊医生接诊后定期删除。主键：分诊科室，诊室名，排队序号，就诊日期
CREATE TABLE HOSPITAL.OUTP_WAIT_QUEUE (
    REGISTER_DEPT      VARCHAR2(8)  NOT NULL,
    QUEUE_NAME         VARCHAR2(16) NOT NULL,
    QUEUE_SEQUENCE     NUMBER(2)    NOT NULL,
    VISIT_NO           NUMBER(4),
    VISIT_DATE         DATE         NOT NULL,
    REGISTER_DATE      DATE,
    WORKED_INDICATOR   NUMBER(1)    DEFAULT 0,
    NAME               VARCHAR2(20),
    CONSTRAINT PK_OUTP_WAIT_QUEUE PRIMARY KEY (REGISTER_DEPT, QUEUE_NAME, QUEUE_SEQUENCE, VISIT_DATE)
);

-- 1.4 科室常用药品 DEPT_COMMON_DRUG
-- 科室常用药品，由科室内医生开处方时共同使用。主键：诊断描述、药品编码
CREATE TABLE HOSPITAL.DEPT_COMMON_DRUG (
    DIANOSIS     VARCHAR2(80) NOT NULL,
    DRUG_CODE    VARCHAR2(10) NOT NULL,
    DEPT_CODE    VARCHAR2(8),
    CONSTRAINT PK_DEPT_COMMON_DRUG PRIMARY KEY (DIANOSIS, DRUG_CODE)
);

-- 1.5 治疗方案模板主记录 TREAT_PROJECT_MASTER
-- 用于定义各种常规治疗方案模板。主键：治疗方案模板标识。
CREATE TABLE HOSPITAL.TREAT_PROJECT_MASTER (
    TREAT_PROJECT_ID  VARCHAR2(6)  NOT NULL,
    TITLE             VARCHAR2(40),
    DEPT_CODE         VARCHAR2(8),
    DIAGNOSIS         VARCHAR2(80),
    ADVICE            VARCHAR2(600),
    CREATOR           VARCHAR2(8),
    CONSTRAINT PK_TREAT_PROJECT_MASTER PRIMARY KEY (TREAT_PROJECT_ID)
);

-- 1.6 治疗方案模板明细 TREAT_PROJECT_ITEMS
-- 治疗方案模板主记录的明细记录。主键：治疗方案模板标识、序号。
CREATE TABLE HOSPITAL.TREAT_PROJECT_ITEMS (
    TREAT_PROJECT_ID  VARCHAR2(6)  NOT NULL,
    ITEM_NO           NUMBER(2)    NOT NULL,
    ORDER_CLASS       VARCHAR2(1),
    ORDER_TEXT        VARCHAR2(80),
    ORDER_CODE        VARCHAR2(10),
    AMOUNT            NUMBER(4),
    SPEC              VARCHAR2(20),
    UNITS             VARCHAR2(8),
    DOSAGE            NUMBER(8,4),
    ADMINISTRATION    VARCHAR2(16),
    FREQUENCY         VARCHAR2(16),
    CONSTRAINT PK_TREAT_PROJECT_ITEMS PRIMARY KEY (TREAT_PROJECT_ID, ITEM_NO)
);
