// <auto-generated />
using System;
using HospitalStats.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalStats.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526025926_FixDashboardCardFK")]
    partial class FixDashboardCardFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("HospitalStats.Api.Models.BizDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BizDomains");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.DashboardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QueryConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QueryConfigId");

                    b.ToTable("DashboardCards");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharSetInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharSetOverride")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QueryConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("QueryConfigId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.MetaColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DataLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataScale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisplayField")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFilterField")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQueryField")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetaTableId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nullable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetaTableId", "ColumnName")
                        .IsUnique();

                    b.ToTable("MetaColumns");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.MetaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BizDomainId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsView")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BizDomainId");

                    b.HasIndex("DataSourceId", "SchemaName", "TableName")
                        .IsUnique();

                    b.ToTable("MetaTables");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateColumn")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupByColumn")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainTableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortColumn")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortDirection")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainTableId");

                    b.ToTable("QueryConfigs");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateFunc")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MetaColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetaColumnId");

                    b.HasIndex("QueryConfigId");

                    b.ToTable("QueryFields");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MetaColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetaColumnId");

                    b.HasIndex("QueryConfigId");

                    b.ToTable("QueryFilters");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JoinTableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftMetaColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueryConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightMetaColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinTableId");

                    b.HasIndex("LeftMetaColumnId");

                    b.HasIndex("QueryConfigId");

                    b.HasIndex("RightMetaColumnId");

                    b.ToTable("QueryJoins");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.DashboardCard", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.QueryConfig", "QueryConfig")
                        .WithMany()
                        .HasForeignKey("QueryConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QueryConfig");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.Menu", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HospitalStats.Api.Models.QueryConfig", "QueryConfig")
                        .WithMany()
                        .HasForeignKey("QueryConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("QueryConfig");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.MetaColumn", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.MetaTable", "MetaTable")
                        .WithMany("Columns")
                        .HasForeignKey("MetaTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaTable");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.MetaTable", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.BizDomain", "BizDomain")
                        .WithMany("Tables")
                        .HasForeignKey("BizDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HospitalStats.Api.Models.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BizDomain");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryConfig", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.MetaTable", "MainTable")
                        .WithMany()
                        .HasForeignKey("MainTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryField", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.MetaColumn", "MetaColumn")
                        .WithMany()
                        .HasForeignKey("MetaColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.QueryConfig", "QueryConfig")
                        .WithMany("Fields")
                        .HasForeignKey("QueryConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaColumn");

                    b.Navigation("QueryConfig");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryFilter", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.MetaColumn", "MetaColumn")
                        .WithMany()
                        .HasForeignKey("MetaColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.QueryConfig", "QueryConfig")
                        .WithMany("Filters")
                        .HasForeignKey("QueryConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaColumn");

                    b.Navigation("QueryConfig");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryJoin", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.MetaTable", "JoinTable")
                        .WithMany()
                        .HasForeignKey("JoinTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.MetaColumn", "LeftMetaColumn")
                        .WithMany()
                        .HasForeignKey("LeftMetaColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.QueryConfig", "QueryConfig")
                        .WithMany("Joins")
                        .HasForeignKey("QueryConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.MetaColumn", "RightMetaColumn")
                        .WithMany()
                        .HasForeignKey("RightMetaColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JoinTable");

                    b.Navigation("LeftMetaColumn");

                    b.Navigation("QueryConfig");

                    b.Navigation("RightMetaColumn");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.RoleMenu", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.UserRole", b =>
                {
                    b.HasOne("HospitalStats.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalStats.Api.Models.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.BizDomain", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.MetaTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.QueryConfig", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Filters");

                    b.Navigation("Joins");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HospitalStats.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
