-- Test data for CLINIC_MASTER matching OUTP_MR
-- Column constraints: NAME=VARCHAR2(8), SEX=VARCHAR2(4), IDENTITY=VARCHAR2(10), CHARGE_TYPE=VARCHAR2(8)
INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-01-15','YYYY-MM-DD'), 1, 'P00001', 'ZhangW', 'M', 45, 'worker', 'YIBAO', 'NORMAL', 'IM', 'Li', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-01-20','YYYY-MM-DD'), 1, 'P00002', 'LiN', 'F', 32, 'worker', 'YIBAO', 'NORMAL', 'SURG', 'Wang', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-02-10','YYYY-MM-DD'), 1, 'P00003', 'WangQ', 'M', 58, 'resident', 'ZIFEI', 'NORMAL', 'ORTH', 'Li', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-02-15','YYYY-MM-DD'), 1, 'P00004', 'ZhaoL', 'F', 27, 'worker', 'YIBAO', 'NORMAL', 'PED', 'Chen', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-02-20','YYYY-MM-DD'), 1, 'P00001', 'ZhangW', 'M', 45, 'worker', 'YIBAO', 'NORMAL', 'IM', 'Li', 5, 10, 15, 2, 0);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-03-01','YYYY-MM-DD'), 1, 'P00005', 'LiuY', 'M', 63, 'retired', 'YIBAO', 'EXPERT', 'CARD', 'Li', 15, 20, 35, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-03-05','YYYY-MM-DD'), 1, 'P00002', 'LiN', 'F', 32, 'worker', 'YIBAO', 'NORMAL', 'IM', 'Wang', 5, 10, 15, 2, 0);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-03-10','YYYY-MM-DD'), 1, 'P00006', 'SunF', 'F', 51, 'resident', 'ZIFEI', 'NORMAL', 'RHEUM', 'Wang', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-03-20','YYYY-MM-DD'), 1, 'P00007', 'ZhouJ', 'M', 41, 'worker', 'YIBAO', 'NORMAL', 'GASTRO', 'Wang', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-04-02','YYYY-MM-DD'), 2, 'P00004', 'ZhaoL', 'F', 27, 'worker', 'YIBAO', 'NORMAL', 'PED', 'Chen', 5, 10, 15, 2, 0);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-04-05','YYYY-MM-DD'), 1, 'P00008', 'WuM', 'F', 36, 'worker', 'YIBAO', 'NORMAL', 'NEPH', 'Chen', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-04-15','YYYY-MM-DD'), 1, 'P00003', 'WangQ', 'M', 58, 'resident', 'ZIFEI', 'NORMAL', 'ORTH', 'Li', 5, 10, 15, 2, 0);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-04-16','YYYY-MM-DD'), 1, 'P00009', 'ChenJ', 'F', 29, 'worker', 'YIBAO', 'NORMAL', 'PSY', 'Wang', 5, 10, 15, 2, 1);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-04-28','YYYY-MM-DD'), 1, 'P00007', 'ZhouJ', 'M', 41, 'worker', 'YIBAO', 'NORMAL', 'DENT', 'Li', 5, 10, 15, 2, 0);

INSERT INTO CLINIC_MASTER (VISIT_DATE, VISIT_NO, PATIENT_ID, NAME, SEX, AGE, IDENTITY, CHARGE_TYPE, CLINIC_TYPE, VISIT_DEPT, DOCTOR, REGIST_FEE, CLINIC_FEE, CLINIC_CHARGE, REGISTRATION_STATUS, FIRST_VISIT_INDICATOR)
VALUES (TO_DATE('2026-05-06','YYYY-MM-DD'), 1, 'P00010', 'ZhengH', 'M', 67, 'retired', 'YIBAO', 'EXPERT', 'RESP', 'Li', 15, 20, 35, 2, 1);

COMMIT;
